# Generated by Django 5.1.3 on 2024-12-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_rename_district_tbl_place_district_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_place',
            old_name='district_id',
            new_name='district',
        ),
    ]
