# Generated by Django 5.1.3 on 2024-12-07 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_localplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_localplace',
            name='district',
        ),
    ]
