# Generated by Django 5.1.3 on 2024-12-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_delete_tbl_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_admin',
            fields=[
                ('admin_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=30)),
                ('admin_email', models.CharField(max_length=40)),
                ('admin_password', models.CharField(max_length=30)),
            ],
        ),
    ]
