# Generated by Django 5.1.3 on 2024-12-13 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KSEB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_ksebupdates',
        ),
    ]
