# Generated by Django 5.1.3 on 2024-12-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MVD', '0002_remove_tbl_updates_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_updates',
        ),
    ]
