# Generated by Django 5.1.3 on 2024-12-07 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0011_remove_tbl_localplace_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_muncipality',
            fields=[
                ('mun_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('mun_name', models.CharField(max_length=30)),
                ('mun_email', models.CharField(max_length=40)),
                ('mun_contact', models.CharField(max_length=30)),
                ('mun_address', models.CharField(max_length=80)),
                ('mun_proof', models.URLField()),
                ('mun_password', models.CharField(max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=80)),
                ('user_email', models.CharField(max_length=40)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_photo', models.URLField()),
                ('user_gender', models.CharField(max_length=30)),
                ('user_dob', models.DateField()),
                ('user_password', models.CharField(max_length=30)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
