# Generated by Django 5.1.3 on 2024-12-07 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_remove_tbl_localplace_district'),
        ('Guest', '0002_tbl_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mvd',
            fields=[
                ('mvd_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('mvd_name', models.CharField(max_length=30)),
                ('mvd_email', models.CharField(max_length=40)),
                ('mvd_contact', models.CharField(max_length=30)),
                ('mvd_address', models.CharField(max_length=80)),
                ('mvd_proof', models.URLField()),
                ('mvd_password', models.CharField(max_length=30)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_district')),
            ],
        ),
    ]
