# Generated by Django 5.1.3 on 2024-12-07 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_remove_tbl_localplace_district'),
        ('Guest', '0003_tbl_mvd'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_kseb',
            fields=[
                ('kseb_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('kseb_name', models.CharField(max_length=30)),
                ('kseb_email', models.CharField(max_length=40)),
                ('kseb_contact', models.CharField(max_length=30)),
                ('kseb_address', models.CharField(max_length=80)),
                ('kseb_proof', models.URLField()),
                ('kseb_password', models.CharField(max_length=30)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
            ],
        ),
    ]
