# Generated by Django 5.1.3 on 2024-12-07 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_tbl_kseb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
