# Generated by Django 5.1.3 on 2024-12-07 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_remove_tbl_localplace_district'),
        ('Guest', '0005_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('user_id', models.TextField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=40)),
                ('user_contact', models.CharField(max_length=30)),
                ('user_address', models.CharField(max_length=80)),
                ('user_photo', models.URLField()),
                ('user_password', models.CharField(max_length=30)),
                ('localplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_localplace')),
                ('muncipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_muncipality')),
            ],
        ),
    ]
