# Generated by Django 5.1.3 on 2024-12-13 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_kseb_kseb_status_tbl_muncipality_mun_status_and_more'),
        ('User', '0004_tbl_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user'),
        ),
    ]
