# Generated by Django 5.1.3 on 2024-12-13 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_tbl_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_like',
        ),
    ]
