# Generated by Django 5.1.3 on 2024-12-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_kseb_kseb_status_tbl_muncipality_mun_status_and_more'),
        ('User', '0009_tbl_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=30)),
                ('request_content', models.CharField(max_length=200)),
                ('request_response', models.CharField(max_length=200)),
                ('request_status', models.IntegerField(default=0)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('kseb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kseb')),
                ('muncipality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_muncipality')),
                ('mvd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
