# Generated by Django 5.1.3 on 2024-12-20 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0007_tbl_kseb_kseb_status_tbl_muncipality_mun_status_and_more'),
        ('User', '0011_remove_tbl_request_kseb_remove_tbl_request_mvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_request',
            name='kseb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_kseb'),
        ),
        migrations.AddField(
            model_name='tbl_request',
            name='mvd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_mvd'),
        ),
    ]
