# Generated by Django 5.1.3 on 2024-12-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0003_tbl_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_munupdates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_content', models.CharField(max_length=100)),
                ('update_date', models.DateField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_complaint')),
            ],
        ),
    ]
